name: Run Robot Test inside Docker Container

on:
  workflow_dispatch:

jobs:
  run_tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Build Docker Image
      run: |
        docker build -t api-automation-ebird >
        docker run --rm api-automation-ebird